name: Skaffold Github Action
description: Setup Skaffold and all required dependencies
author: hiberbee
branding:
  icon: anchor
  color: blue
inputs:
  skaffold-version:
    default: 1.31.0
    description: Set Skaffold version
    required: false
  container-structure-test-version:
    default: 1.10.0
    description: Set Container Structure Test version
    required: false
  command:
    default: version
    description: Skaffold command to execute
    required: true
  build-image:
    default: ''
    description: Choose which artifacts to build. Artifacts with image names that contain the expression will be built only. Default is to build sources for all artifacts
    required: false
  cache-artifacts:
    default: 'true'
    description: Set to false to disable default caching of artifacts
    required: false
  default-repo:
    default: ''
    description: Default repository value (overrides global config)
    required: false
  filename:
    default: skaffold.yaml
    description: Path or URL to the Skaffold config file
    required: false
  kubeconfig:
    default: ''
    description: Path to the kubeconfig file to use for CLI requests
    required: false
  kube-context:
    default: ''
    description: Deploy to this Kubernetes context
    required: false
  working-dir:
    default: ''
    description: Set current working directory similar to Github Actions run
    required: false
  profile:
    default: ''
    description: Activate profiles by name (prefixed with `-` to disable a profile)
    required: false
  skip-tests:
    default: 'true'
    description: Whether to skip the tests after building
    required: false
  tag:
    default: ''
    required: false
    description: The optional custom tag to use for images which overrides the current Tagger configuration
outputs: {}
runs:
  using: node12
  main: src/index.js
